In [38]:
import numpy as np

# how to create an empty and a full numpy array?

In [39]:
a = np.empty((3, 4))
print(a)

[[1.05828967e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.14587773e-312 1.33664410e+160 7.72844292e-091 4.27629970e-033]
 [3.61014451e+174 7.35366412e-043 3.99910963e+252 1.90979636e-312]]


# create numpy array filled with all zeros?

In [40]:
a=np.zeros(3)
print(a)

[0. 0. 0.]



# created a numpy array filled with all ones

In [41]:
a = np.ones(2)
a

array([1., 1.])

# created whether a numpy  array contains a specified row

In [42]:

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


_row = np.array([4, 5, 6])


if any(np.array_equal(row, _row) for row in array):
    print("Specified row is in the array.")
else:
    print("Specified row is not in the array.")


Specified row is in the array.



# how to remove rows in numpy array that contains non-numeric values


In [50]:
n_arr = np.array([[10.5, 22.5, 3.8], 
                  [41, np.nan, np.nan]]) 
  
print("Given array:") 
print(n_arr) 
  
print("\nRemove all rows containing non-numeric values") 
print(n_arr[~np.isnan(n_arr).any(axis=1)]) 

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric values
[[10.5 22.5  3.8]]


# remove single-dimensional entries from the shape of an array

In [43]:
a

array([1., 1.])

In [44]:
a.shape

(2,)

# find the number of occurrences of a sequence in a numpy array 

In [45]:
b = np.array([[2, 3, 4],[2,4,5]])
b

array([[2, 3, 4],
       [2, 4, 5]])

In [46]:
 
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print(x) 
print("Most frequent value  array:") 
print(np.bincount(x).argmax())

[1 2 3 4 5 1 2 1 1 1]
Most frequent value  array:
1


# combining a one and a two-dimensional numpy array

In [47]:
import numpy as np


one = np.array([1, 2, 3])


two = np.array([[4, 5, 6],
                          [7, 8, 9]])
combined_array = np.vstack((one, two))
print(combined_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


# how to bulid an array of all combinations of two numpy arraays?

In [48]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

_array1, _array2 = np.meshgrid(array1, array2)

combinations = np.vstack((_array1.ravel(), _array2.ravel())).T

print(combinations)


[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]
 [1 6]
 [2 6]
 [3 6]]
